version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app    # Mounts your current directory to /app in container
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload